ci: upgrade Nix from 2.3.12 to 2.5.1
Due to changes in how Nix handles Git refs we need to specify
`refs/tags/` prefix in `package.json` to avoid the following error:
```
fatal: couldn't find remote ref refs/heads/v2.0.3-status-v6
error: program 'git' failed with exit code 128
```
Resolves: https://github.com/status-im/status-react/issues/12832
Issue: https://github.com/NixOS/nix/issues/5291

Signed-off-by: Jakub Sokołowski <jakub@status.im>